;	 PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;

; Dave Williams, DitroniX 2019-2026 (ditronix.net)
; IPEM NB-IoT | ESP32C5 ATM90E36 SIM7070G GPRS IoT LTE-M GNSS Mains Power Energy Monitor

; July 2026: Example Code, to demonstrate and test the IPEM NB-IoT

; Remember!
; - Set the BOARD to Use ESP32C5 Dev Module (or similar).
; - You can also set the BAUD rate up to 921600 to speed up flashing.
; - The SDK does NOT need external power to flash.  It will take Power from the USB 5V.
; - The Serial Monitor is configured for BAUD 115200

; The purpose of this test code is to cycle through the various main functions of the board as part of bring up testing.

; This test code is OPEN SOURCE and formatted for easier viewing.  Although is is not intended for real world use, it may be freely used, or modified as needed.
; It is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

; For board configuration, see https://github.com/DitroniX/IPEM-NBIoT-ESP32C5-ATM90E36-SIM7070G-GPRS-IoT-Mains-Power-Energy-Monitor/wiki/Arduino-IDE 

; Further information, details and examples can be found on our website or github.com/DitroniX

; * ditronix.net
; * github.com/DitroniX
; * github.com/DitroniX/IPEM-NBIoT-ESP32C5-ATM90E36-SIM7070G-GPRS-IoT-Mains-Power-Energy-Monitor
; * github.com/DitroniX/IPEM-NBIoT-ESP32C5-ATM90E36-SIM7070G-GPRS-IoT-Mains-Power-Energy-Monitor/wiki
; * hackster.io/DitroniX/ipem-nb-iot-esp32c5-m90e36-sim7070g-iot-mains-power-monitor-40096e

; 	https://github.com/DitroniX/IPEM-NBIoT-ESP32C5-ATM90E36-SIM7070G-GPRS-IoT-Mains-Power-Energy-Monitor/wiki/ATM90E36-Registers 

; [platformio]
; default_envs = development

[env:esp32c5]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c5-devkitc-1
framework = arduino

upload_speed = 921600
monitor_speed = 115200

; Optional Fixed Com Port. This is useful if you have other COM devices and Auto does not work.
; upload_port = COM68
; monitor_port = COM68

; ---------------------------------------------------------------------

; Optional Automatic COM Port from a specific range.  INCLUDE COM ports 17-99.  EXCLUDE any COM ports 0-16.
; def get_valid_range_port():
;     # Scan all active, plugged-in system ports
;     active_ports = serial.tools.list_ports.comports()
    
;     for port in active_ports:
;         port_name = port.device.upper()
        
;         # INCLUDE: ly ports from COM17 through COM99
;         # EXCLUDE: (1[7-9] handles 17-19, and [2-9][0-9] handles 20-99)
;         match = re.match(r'^COM(1[7-9]|[2-9][0-9])$', port_name)
;         if match:
;             print(f"--- [Range Filter] Selected Valid Port: {port_name} ---")
;             return port.device
            
;     return None

; # Find an available port that meets your criteria
; valid_port = get_filtered_port()

; if valid_port:
;     # Inject the actual physical string name to prevent tool pathing errors
;     env.Replace(UPLOAD_PORT=valid_port)
;     env.Replace(MONITOR_PORT=valid_port)
; else:
;     print("--- [Filter Warning] No active devices found within COM17-COM99 (excluding COM16) ---")

; ---------------------------------------------------------------------

lib_deps = 
	gyverlibs/GyverOLED@^1.6.1
	adafruit/Adafruit NeoPixel @ ^1.15.5
	
